### ISSUE TITLE
Variables and Assignment section missing some of the Key Points

### ISSUE THREAD

**Issue by kathys** [UW-Madison-DataScience/python-novice-gapminder-custom#9]
When going through this boot camp, it is good, but when I get to the end of the Variables and Assignment section, the Key Points include these bullets:

Use an index to get a single character from a string.
Use a slice to get a substring.
Use the built-in function len to find the length of a string.

However, this section never actually teaches how to do these things.

**Comment by sstevens2** [comment]
Thanks for reporting @kathys.  We removed the early lessons since they can be found [here](http://swcarpentry.github.io/python-novice-gapminder/).
